### ISSUE TITLE
unicode characters

### ISSUE THREAD

**Issue by StasD** [AlexCovizzi/vscode-sqlite#1]
Hello,
Your fix for the issue which I pointed in the review does not seem to work...
Now nothing happens when I select "show table" on a table which contains unicode text. Looks like it just fails silently somewhere... Running corresponding queries from .sql file also does not work.
For tables with English-only characters it still works.
I'm using a Mac, btw (though should not make a difference).

**Comment by AlexCovizzi** [comment]
can you go to Help > Toggle developer tools > Console
and then select 'show table' and tell me what error is shown?

**Comment by StasD** [comment]
```
Error: Running the contributed command:'sqlite.showQueryResult' failed.
	at e._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:674:709)
	at e.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:673:944)
	at Object.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:739:963)
	at queryRunner.runQuery.then.resultSet (/Users/stas/.vscode/extensions/alexcvzz.vscode-sqlite-0.0.2/out/mainController.js:137:88)
	at <anonymous>
```

. | .
-- | --
e.$onExtensionRuntimeError | @ mainThreadExtensionService.ts:44
e._doInvokeHandler | @ rpcProtocol.ts:265
e._invokeHandler | @ rpcProtocol.ts:250
e._receiveRequest | @ rpcProtocol.ts:196
e._receiveOneMessage | @ rpcProtocol.ts:178
(anonymous) | @ rpcProtocol.ts:111
(anonymous) | @ rpcProtocol.ts:307
e.fire | @ event.ts:140
(anonymous) | @ ipc.net.ts:81
emitOne | @ events.js:96
emit | @ events.js:191
readableAddChunk | @ _stream_readable.js:178
Readable.push | @ _stream_readable.js:136
onread | @ net.js:560

**Comment by AlexCovizzi** [comment]
fixed it, thanks for the help

**Comment by StasD** [comment]
Here is how it looks now: :)
![How it looks](https://s3-eu-west-1.amazonaws.com/stas-ie/photos/vscode_sqlite_1.png)

And this is how it should look...
![How it should looks](https://s3-eu-west-1.amazonaws.com/stas-ie/photos/vscode_sqlite_2.png)

So, the fix only worked for simple cases like "français", but not unicode in general, e.g. "汉语".

**Comment by AlexCovizzi** [comment]
it should work now, i tested it with a table similar to yours and it seems to work.
Thanks again for your help

**Comment by StasD** [comment]
Yep, looks good now!

**Comment by Zigby** [comment]
Thanks for the update. It also solved my issue with columns of type blob which apparently did not always generate well formed html causing nothing to be displayed. Columns of type guid are however not presented as guids like some Sqlite tools are able to do. I guess this cannot be seen as an issue (guid not being a really supported rather stored as blob) but it would be very useful feature addition to this awesome extension to vs code.

<img width="361" alt="skarmavbild 2018-06-26 kl 20 43 25" src="https://user-images.githubusercontent.com/28486683/41932598-a589235a-7981-11e8-84f2-fa175f71f9c6.png">
