### ISSUE TITLE
Query on larger tables do not display

### ISSUE THREAD

**Issue by psychelzh** [AlexCovizzi/vscode-sqlite#10]
I have a table which has thousands of records. And it cannot be displayed using `Show Table`. But using other tools I can visualize it.

**Comment by AlexCovizzi** [comment]
I just published a minor release where i fixed the issue.
I tested it on a table with 10000 records and it seems to work, on my laptop (i3-3110M, 4GB Ram) it's extremely slow though since it renders all 10000 records in the same page.
I will add paging for larger tables soon, for now i suggest you use custom queries.

**Comment by psychelzh** [comment]
I have seen the latest release. Unfortunately, after this update, I could not view any tables now.

**Comment by AlexCovizzi** [comment]
You mean you can't even see smaller tables?

**Comment by psychelzh** [comment]
Yes. The pane popped out but nothing displayed.

**Comment by psychelzh** [comment]
Thanks! @AlexCovizzi Now I can view small tables, but still no way for large tables.

![image](https://user-images.githubusercontent.com/13306020/42623390-54b459b0-85f5-11e8-92ca-ed9539231bfd.png)

What's more, the export to `.csv` and `.json` seems not working, either.

**Comment by psychelzh** [comment]
I have tested, and I can confirm that I can view a table that has about 5,000 rows. Then I find out that I have a table that has more than 50,000 rows, which can not be viewed this way.

**Comment by AlexCovizzi** [comment]
Support for larger tables will come soon (probably later today).

> What's more, the export to .csv and .json seems not working, either.

Can you tell me more about this? Does it not work completely or the exported files are incorrect?

**Comment by psychelzh** [comment]
Export does not work completely. Since nothing happened when I click on the icon.

**Comment by AlexCovizzi** [comment]
i fixed the export issue, and added support for large tables. I tested it with a table with 10000 records and it works fine, it's still a little slow to load tough (but not as slow as before).

**Comment by psychelzh** [comment]
Great, export works now! The table view is also faster. By the way, what is the maximal number of records supported now?

**Comment by AlexCovizzi** [comment]
There is a limit on the output buffer, right now it's at 2MB. I'll add a setting to change it though, in case more is needed.

**Comment by psychelzh** [comment]
Will it be okay for users to set the buffer limit? Some of my database tables have more than 50,000 records, which need a larger buffer.

**Comment by AlexCovizzi** [comment]
Done, you can now change the buffer limit with the setting `sqlite.outputBuffer`.

**Comment by psychelzh** [comment]
I have a better idea for displaying larger datasets. We could set a maximal number of rows for preview, say, 1000 rows. And a message warning users that the real number of rows is larger for non-complete preview will be really nice.

**Comment by AlexCovizzi** [comment]
I'm rewriting some of the main parts to be faster and more responsive, it should be ready in a few days.

The setting ```outputBuffer``` will also be removed because it won't be necessary anymore.
