### ISSUE TITLE
Remote Server with SQLite DB (RQLite)

### ISSUE THREAD

**Issue by nunotavares** [AlexCovizzi/vscode-sqlite#103]
Hey guys.
Is it possible to connect your extension to a remote SQLite Database.

The DB is on another server and for purposes of doing queries and check the tables it would be nice if this extension supports that.

Cheers,

**Comment by AlexCovizzi** [comment]
Hi @nunotavares , the extension does not support RQLite.
It is however possible to use the extension remotely together with other extensions like Remote SSH or Remote WSL.

**Comment by AlexCovizzi** [comment]
To add on my answer, I looked at the RQLite command line interface and it doesn't seem to support CSV output, that makes it extremely difficult to parse and to integrate on the extension.
