### ISSUE TITLE
[Feature request] Execute Current Statement

### ISSUE THREAD

**Issue by Kimbahir** [AlexCovizzi/vscode-sqlite#104]
Support for executing the statement the cursor is currently placed in. It's available in the "SQL server" addon and an awesome feature in say Toad or Oracle SQL Developer. 

The value is inherent if you are crafting your SQL statements and are exploring data and thus have multiple statements in the same file. It makes life easier :)

Also, great plugin so far :)

**Comment by AlexCovizzi** [comment]
Hi @Kimbahir, this function is already available with #13: placing the cursor on the statement you want to run and left click > Run Selected Query (or commands > Run Selected Query), the extension will only run that statement.
Feel free to reopen if you are having problem with this feature!

**Comment by Kimbahir** [comment]
Hi @AlexCovizzi, I feel so stupid - was trying with Run Query - works like a charm. Thanks a bunch
