### ISSUE TITLE
Howto enable?

### ISSUE THREAD

**Issue by rosendaldk** [AlexCovizzi/vscode-sqlite#105]
How do I get the command line to pop up to open database?
Should there be a gui way of doing this?

**Comment by AlexCovizzi** [comment]
Hi @rosendaldk, you can open a database by right clicking on it and then selecting `Open Database`, this will open the database in the explorer.
Another way to open the database is to open the Command Palette (usually by pressing `F1`) and then using the command `SQLite: Open Database`, and selecting the database you want to open (from the list or from you files).

**Comment by AlexCovizzi** [comment]
Feel free to reopen if this didn't answer you question

**Comment by rosendaldk** [comment]
Thanks a lot
