### ISSUE TITLE
Uses a CLI binary?

### ISSUE THREAD

**Issue by wmertens** [AlexCovizzi/vscode-sqlite#116]
I just discovered this extension, and it's fun that I can check out databases in VSCode now, but I'm wondering why you chose to work via an external binary when a library like https://github.com/JoshuaWise/better-sqlite3 provides super-fast direct access?

**Comment by AlexCovizzi** [comment]
Hi @wmertens, unfortunately [VSCode doesn't provide a way to install native dependencies](https://github.com/microsoft/vscode/issues/6929), so node sqlite libraries are not an option.
The only viable solution I could find was to use the sqlite command line interface, it's not quite as fast as a native library, but it's fast enough for most use cases.
Usually by the time the WebView is loaded, the query has already been executed and the output has already been parsed.

**Comment by wmertens** [comment]
Wow? I know that vs live uses native binaries, are they cheating?

In the issue you linked, the extension seems to use the workaround of installing the binary dependencies on the first run? I can't really tell...

**Comment by wmertens** [comment]
I just had a look at my installed extensions, and https://github.com/flowtype/flow-for-vscode/blob/master/package.json has a dependency on `flow-bin`, which installs a binary, and I don't see anything that tells vscode to treat it in a special way?

**Comment by AlexCovizzi** [comment]
If you look in the extension folder (`~/.vscode/flow-for-vscode...`) you'll see that the binaries are packaged with the extension (and not installed), you can find them in `node_modules/flow-bin`.

**Comment by wmertens** [comment]
Aha ok, thank you, that's terrible :(

**Comment by wmertens** [comment]
Ok, so the official approach seems to be that you should install native dependencies on activation https://github.com/microsoft/vscode/issues/23251#issuecomment-406090410, and supposedly the Marketplace team will eventually provide some declarative solution

**Comment by AlexCovizzi** [comment]
In the comment the Live Share extension is used as example, I took a look at the Live Share extension in my `~/.vscode/extensions` folder and it seems to download some executables, so not native dependencies
