### ISSUE TITLE
Search databases by path instead of name in the database picker

### ISSUE THREAD

**Issue by wmertens** [AlexCovizzi/vscode-sqlite#117]
I have a bunch of databases at `./data/*/data.sqlite3`, and the extension finds them (yey!) but I can't type the `*` part to get the database I want (aww).

Would it be possible to have the path be part of the typeahead search?

**Comment by AlexCovizzi** [comment]
You mean that you have a bunch of database with the same name in different folders and you'd like to be able to search based on the folder instead of the database name?

**Comment by wmertens** [comment]
Yes, correct :)

**Comment by AlexCovizzi** [comment]
Done in #154
