### ISSUE TITLE
Error: "Unable to find a valid SQLite command. Fallback binary is not valid." on activating extension

### ISSUE THREAD

**Issue by giulianusslourencon** [AlexCovizzi/vscode-sqlite#118]
I'm using the SQLite version 0.8.2 on VSCode 1.45.1 on Linux Mint.
This error occurs every time the extension is being activated and don't let me use any of its functionalities, besides the extension get activated.

![image](https://user-images.githubusercontent.com/39507204/83571307-e9896c00-a4fd-11ea-9ca1-f536491709f4.png)

When I try to open a database, I get the error: "**Database failed to open: SQLite process failed to start: The argument 'file' cannot be empty. Received ''**"

![image](https://user-images.githubusercontent.com/39507204/83571414-163d8380-a4fe-11ea-9148-6fc9278a2037.png)

**Comment by davigdc** [comment]
I had the same error message, I also use linux (pop_os 20.04).
This was the solution for me:

1º -  `sudo apt-get install sqlite3`
2ª  restart vscode

I hope I can help.

**Comment by giulianusslourencon** [comment]
It worked, thank you =D
