### ISSUE TITLE
Save entire result page

### ISSUE THREAD

**Issue by fotospiro** [AlexCovizzi/vscode-sqlite#12]
Add the "Save Result Page" feature to save entire result page into a single html page (also remember that vscode cannot print), or copy it to clipboard.

Save all this (not only export single queries):
![schermata 2018-07-20 alle 11 25 21](https://user-images.githubusercontent.com/40659655/42994889-aac64816-8c0f-11e8-87cb-904c9eff1539.png)

**Comment by AlexCovizzi** [comment]
ok, can you be more specific? You mean save everything including javascript and css or just the html tables?

**Comment by fotospiro** [comment]
I think only html. Goal is paste tables with relative columns and table headers into a document like Word.

**Comment by AlexCovizzi** [comment]
added on release 0.3.0, you can export single result or entire page as html
