### ISSUE TITLE
when show table second time, it does not work, nothing to show

### ISSUE THREAD

**Issue by lisonge** [AlexCovizzi/vscode-sqlite#120]
![GIF 2020-7-16 1-42-22](https://user-images.githubusercontent.com/38517192/87577899-30c26980-c706-11ea-93c7-891641b18eb0.gif)

**Comment by Xantim** [comment]
Two more people in my class also ran into this!  Thanks for looking into it!

**Comment by weslleyalmeid** [comment]
I'm also having this problem and I know a few more people who are also having the same problems

**Comment by AlexCovizzi** [comment]
@weslleyalmeid @Xantim @lisonge I'll look into it this weekend, in the meantime, can you share the logs? In the configuration set "sqlite.logLevel": "DEBUG" and then run the command "SQLite: Show Output", thanks

**Comment by weslleyalmeid** [comment]
> @weslleyalmeid @Xantim @lisonge I'll look into it this weekend, in the meantime, can you share the logs? In the configuration set "sqlite.logLevel": "DEBUG" and then run the command "SQLite: Show Output", thanks

first I run at 10:12 AM which worked perfectly, then I closed the side flap and at 10:13 I ran the command again and at that moment it didn't work, follow the log link [SQLite: Show Output](https://gist.github.com/weslleyalmeid/90704c3fd79eaa5a7f1671ccff197087)

**Comment by lisonge** [comment]
@AlexCovizzi 

log record

![2020-07-23 12-25-36](https://user-images.githubusercontent.com/38517192/88275950-cc5c6700-cd10-11ea-8211-e2265fb23b5a.gif)

log output

```
[下午12:25:07][vscode-sqlite][INFO] Activating extension vscode-sqlite v0.8.2...
[下午12:25:07][vscode-sqlite][INFO] Extension activated.
[下午12:25:11][vscode-sqlite][DEBUG] SQLite3 command: 'sqlite3'
[下午12:25:11][vscode-sqlite][DEBUG] Database path: 'e:\Documents\Projects\pixiv-bucket\assets\illust-info.db'
[下午12:25:11][vscode-sqlite][DEBUG] Query: SELECT * FROM `artwork`;
[下午12:25:11][vscode-sqlite][DEBUG] Statements:
[{"sql":"SELECT * FROM `artwork`;","position":{"start":[0,0],"end":[0,23]},"type":"SELECT"}]
[下午12:25:16][vscode-sqlite][DEBUG] SQLite3 command: 'sqlite3'
[下午12:25:16][vscode-sqlite][DEBUG] Database path: 'e:\Documents\Projects\pixiv-bucket\assets\illust-info.db'
[下午12:25:16][vscode-sqlite][DEBUG] Query: SELECT * FROM `artwork`;
[下午12:25:16][vscode-sqlite][DEBUG] Statements:
[{"sql":"SELECT * FROM `artwork`;","position":{"start":[0,0],"end":[0,23]},"type":"SELECT"}]
```

sqlite file: [google drive](https://drive.google.com/file/d/1DEYSGjQIdYkUnXlaOWmuect2TBOjoaVO/view?usp=sharing)

but i think this log is useless

**Comment by AlexCovizzi** [comment]
Looked into it, apparently the webview resources are not found the second time, maybe something was changed in th way that VSCode loads the resources, anyway I'm rewriting that part so it should be fixed in the next release

**Comment by luciano-schirmer** [comment]
Same issue here!

> Looked into it, apparently the webview resources are not found the second time, maybe something was changed in th way that VSCode loads the resources, anyway I'm rewriting that part so it should be fixed in the next release

Thanks
