### ISSUE TITLE
exec only selected text

### ISSUE THREAD

**Issue by fotospiro** [AlexCovizzi/vscode-sqlite#13]
Exec only selected text (also if it's inside a comment), so we don't have to reedit script.

exec only "SELECT * FROM sqlite_master;"
![schermata 2018-07-25 alle 14 15 17](https://user-images.githubusercontent.com/40659655/43200252-3d246716-9015-11e8-9e58-e8ffd633fe53.png)

exec only "select * from tokens;"
![schermata 2018-07-25 alle 14 11 51](https://user-images.githubusercontent.com/40659655/43200209-0d869664-9015-11e8-94ad-58b2540c7890.png)

**Comment by tnatanael** [comment]
+1 S2

**Comment by tnatanael** [comment]
Sugestion: keyboard shortcut to execute entire query file or only selected text, also put the keyboard shortcut to this action in context menu with mouse right click...

![image](https://user-images.githubusercontent.com/11818318/44216390-30e91180-a14b-11e8-8c57-05c295017ec0.png)

**Comment by AlexCovizzi** [comment]
added on release 0.3.0, if you are selecting some text when running the query, it will only run the selected text
