### ISSUE TITLE
Add to activity bar

### ISSUE THREAD

**Issue by PaulEbose** [AlexCovizzi/vscode-sqlite#133]
I really like this extension and I have been using it for a while. It will be nice to have it show in the Activity Bar, as navigation will be way easier and the vscode workspace be less busy

**Comment by AlexCovizzi** [comment]
Hi @PaulEbose! I'll take a look if I'm able to add it to the activity bar in a way that makes sense. The idea is that the extension should be as unobtrusive as possible and I think adding it to the activity bar goes against this idea. Additionally I think it would require to take a different approach on some things

**Comment by PaulEbose** [comment]
lol, a lot has happened since I created this issue. I am now used to the layout and I may prefer it as it just works perfectly without being too much. Any decision you make will be a solid one. It is a really awesome extension regardless
