### ISSUE TITLE
The SQLite Sidebar explorer is missing

### ISSUE THREAD

**Issue by csmibrahim** [AlexCovizzi/vscode-sqlite#134]
Hi,
The Sidebar explorer does not seams to work.  Also is not on the explorer list.

vscode-sqlite 0.9.0 (22 Aug 2020) and Code 1.50.1

**Comment by AlexCovizzi** [comment]
Hey @csmibrahim! Really sorry for the late response, the database should be opened in the explorer, if that's not the case check that the sqlite explorer is enabled by right clicking on the explorer bar:
![explorer](https://user-images.githubusercontent.com/16863733/98440448-07847980-20f9-11eb-9dde-1a9910583469.png)

**Comment by cheffe** [comment]
I do have the same problem. After installing the extension and restarting code, SQLite Explorer does not show up when right clicking on the explorer bar.

**Comment by AlexCovizzi** [comment]
The explorer becomes visible only after opening a database, that is after right clicking on a database and selecting `Open Database`, after that the explorer should be visible
