### ISSUE TITLE
database file chooser shouldn't exclude by suffix

### ISSUE THREAD

**Issue by alex116** [AlexCovizzi/vscode-sqlite#139]
I have a file named mydatabase.sql but can't open it because the file chooser filter is probably set to *.db.  
I don't want to rename my file.  
Could you please add \*.\*?

**Comment by AlexCovizzi** [comment]
Hi @alex116!
By default the files with the following extensions are recongnized as sqlite databases: `.db`, `.db3`, `.sdb`, `.s3db`, `.sqlite`, `.sqlite3`
However you can change this using the configuration `sqlite.databaseExtensions`, here you can add `.sql` to the list and it should be recognized as an sqlite database.
Note that this will work only when opening the database from the command palette with the command SQLite: Open Database, the .sql extension will still not be recognized if you try to open the database from the file explorer (Right click on the file > Open Database)

**Comment by AlexCovizzi** [comment]
Closing this issue.
Feel free to reopen @alex116 if my answer wasn't clear or if that didn't answer your question

**Comment by zinen** [comment]
@AlexCovizzi I would love if you would support extension '.*' as a dropdown choice in file explorer open menu. As a result when non standard naming of databases are used. 

I guess this request is also kinda like issue #69 simi fixed in version 0.7.0 with `sqlite.databaseExtensions` settings.
