### ISSUE TITLE
Enhancement : consider sql.js

### ISSUE THREAD

**Issue by calumk** [AlexCovizzi/vscode-sqlite#144]
Consider migration / use of of sql.js, to remove dependancy on user provided binary of sqlite3

https://github.com/sql-js/sql.js

**Comment by AlexCovizzi** [comment]
Hey @calumk! Thanks for the suggestion!
I did take a look at this library when I first started making the extension, but I didn't really like that it has to load the database in memory at the start so I ended up with the current solution, hopefully VSCode will support native libraries for extensions so I will be able to use better solutions like https://www.npmjs.com/package/sqlite3

**Comment by calumk** [comment]
Fair point! :)
