### ISSUE TITLE
Please setup GitHub Sponsors so I can sponsor you!

### ISSUE THREAD

**Issue by thadguidry** [AlexCovizzi/vscode-sqlite#146]
What an amazing extension, which even works right from within WSL (ubuntu) as long as you install sqlite `apt-get install sqlite` !
The table visualization and export to CSV, JSON, HTML are exactly what I even needed and completely unexpected!

I'd love to sponsor your organization or as individuals if you wish to apply to GitHub Sponsers.
Let me know if I can help. I've done the setup for our [OpenRefine](https://github.com/OpenRefine/OpenRefine) organization and project.

**Comment by AlexCovizzi** [comment]
Hey @thadguidry! I'm glad you like the extension!
Thanks for the suggestion, I'll take a look on how to set it up

**Comment by AlexCovizzi** [comment]
I thought about it but I don't think I'll setup Github sponsors for this project, the reason is that I work on it very sparsely and when I feel like it, so it doesn't seem fair being sponsored
Thank you anyway!
