### ISSUE TITLE
Unable to display table contents. 

### ISSUE THREAD

**Issue by jrodguez** [AlexCovizzi/vscode-sqlite#150]
First time using the extension. I was able to successfully create tables in a database, but when I went to import data from csv into the tables, the tables were not displayed afterwards. The data import works correctly when running on terminal, but not within the extension.

**Comment by AlexCovizzi** [comment]
Hi @jrodguez, the extension currently does not support importing data from csv to a table

**Comment by jrodguez** [comment]
Ah thank you, I did not realize that!
