### ISSUE TITLE
Vulnerability Reporting Process

### ISSUE THREAD

**Issue by ashdoeshax** [AlexCovizzi/vscode-sqlite#156]
Hello, could you please let me know how to best report a security vulnerability in this project. It may be good to document your preferred method here - https://github.com/AlexCovizzi/vscode-sqlite/security

**Comment by AlexCovizzi** [comment]
Hi @ashdoeshax, sorry for the late response, I added a SECURITY.md file to the repository.
The preferred way to report a vulnerability is sending an email explaining the issue at alexcovizzi+github@gmail.com
