### ISSUE TITLE
Update on support for dot commands?

### ISSUE THREAD

**Issue by kburchfiel** [AlexCovizzi/vscode-sqlite#163]
Hey Alex,

Thank you so much for creating this extension--it has been a huge help to me on my SQLite3 learning journey.

I saw your [2019 post on dot commands](https://github.com/AlexCovizzi/vscode-sqlite/issues/81) and wanted to check and see whether there are any updates on present/future support for dot commands. It would be great to be able to use commands like .import, .mode csv, .schema, and .tables in Visual Studio Code.

Thanks!

**Comment by AlexCovizzi** [comment]
Support for dot commands has been added in version 0.13.0
