### ISSUE TITLE
Error loading webview, VScode 1.58

### ISSUE THREAD

**Issue by julia-kurganskaia** [AlexCovizzi/vscode-sqlite#177]
VScode was updated today. 

```
Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:53:55.113Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-59-generic snap
```
The extension version is 0.13.0.

Before VScode update it was working fine, but after update I got this error:

```
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

**Comment by AlexCovizzi** [comment]
Hi @julia-kurganskaia, have you tried uninstalling and reistalling the extension?

**Comment by julia-kurganskaia** [comment]
Good morning @AlexCovizzi , yes, I uninstalled and reinstalled the extension, but I still get the same error.

**Comment by AlexCovizzi** [comment]
Looks like this and similar errors started to pop up from version 1.56 of VSCode, do you get the same error for any other extension that uses webviews (for example Git History)?
It would be also useful if you can post the stacktrace

**Comment by julia-kurganskaia** [comment]
Hi @AlexCovizzi , I have not changed anything, but it doesn't throw err anymore. Thank you.
