### ISSUE TITLE
create trigger only works when /* */ is in query

### ISSUE THREAD

**Issue by DNoel26** [AlexCovizzi/vscode-sqlite#195]
I have the query below: 

This works...

CREATE TRIGGER IF NOT EXISTS trigger_bar /* */
AFTER UPDATE ON foo
BEGIN
    UPDATE foo
    SET updated_at = DATETIME('now')
    WHERE id = NEW.id; 
END;

End of debug statement: WHERE id = NEW.id;","position":{"start":[0,0],"end":[6,21]},"type":"OTHER"},{"sql":"END;","position":{"start":[6,23],"end":[6,26]},"type":"OTHER"}] 

Bu this doesn't work...

CREATE TRIGGER IF NOT EXISTS trigger_bar
AFTER UPDATE ON foo
BEGIN
    UPDATE foo
    SET updated_at = DATETIME('now')
    WHERE id = NEW.id; 
END;

End of debug statement: WHERE id = NEW.id; \nEND;","position":{"start":[0,0],"end":[0,0]},"type":"OTHER"}]

Why does it only work when I include a random comment in the query? I have outlined the only differences in the debug console for each situation above. I don't really understand what the position references but that's what I picked up.

**Comment by pongbao** [comment]
OMG I tried this and my code worked what?!

**Comment by AlexCovizzi** [comment]
Fixed in 0.14.1
