### ISSUE TITLE
Table view does not work in vscode 1.62

### ISSUE THREAD

**Issue by harryjjun** [AlexCovizzi/vscode-sqlite#196]
Table view in the django application is not working after updating [vscode 1.62](https://code.visualstudio.com/updates/v1_62)

<img width="286" alt="Snipaste_2021-11-05_14-47-35" src="https://user-images.githubusercontent.com/18046097/140464439-d5d59217-4046-4972-9f86-c551ac3fa30b.png">

<img width="977" alt="Snipaste_2021-11-05_14-44-52" src="https://user-images.githubusercontent.com/18046097/140464454-257ae81f-1fe2-422a-9d93-389067559ea4.png">

**Comment by ShvetsBy** [comment]
The issue

**Comment by dev-simonbailey** [comment]
Same here, I'm afraid.

Working Great.
VSCode: 1.57.0
SQLite: 0.13.0

No Table View
VSCode: 1.62.0
SQLite: 0.13.0

**Comment by rauldel** [comment]
Hello there 👋 ,
I have the same issue here, with the exact same VSCode information like @harryjjun 

`Version: 1.62.0 (user setup)
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-03T15:23:01.379Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042`

`SQLite version: 0.13.0`

Best regards
