### ISSUE TITLE
Db won't open

### ISSUE THREAD

**Issue by danyelchidera** [AlexCovizzi/vscode-sqlite#198]
my slqlite does not open tables, instead I get

`[vscode-sqlite][DEBUG] 'sqlite3' is not a valid SQLite command: Error: spawnSync sqlite3 ENOENT`

version 0.13.0
OS: windows

**Comment by cmarango** [comment]
Experiencing the same issue.  Seems to have appears after latest vscode update (1.62)

**Comment by klawrow** [comment]
Same issue on macOS 12.0.1, so yeah leaning on latest vscode update

**Comment by klawrow** [comment]
Looks like there is a PR on this issue... https://github.com/AlexCovizzi/vscode-sqlite/pull/197
