### ISSUE TITLE
Table order in Explorer Tree

### ISSUE THREAD

**Issue by fotospiro** [AlexCovizzi/vscode-sqlite#2]
Sort tables by name in Explorer Tree (file src/explorer/explorerTreeProvider.ts, line 51)

![schermata 2018-06-28 alle 11 33 59](https://user-images.githubusercontent.com/40659655/42026379-3fd4df94-7ac7-11e8-99b8-d60acb66c962.png)

![schermata 2018-06-28 alle 11 32 11](https://user-images.githubusercontent.com/40659655/42026262-f1360296-7ac6-11e8-816e-f00d516c34cf.png)

**Comment by AlexCovizzi** [comment]
it's implemented in the dev branch, i'll publish it soon
