### ISSUE TITLE
Does not work on VS Code 1.26.1 for Windows

### ISSUE THREAD

**Issue by Praful** [AlexCovizzi/vscode-sqlite#20]
Hello

I tried to open a database but nothing happens. I assume the process is to press Ctrl/Shift/P, select `SQLite: Open Database in Explorer`, then enter the full path of the Sqlite database eg `c:\temp\mydata.sqlite`.

My VS Code details are:

- Version: 1.26.1
- Electron: 2.0.5
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41
- Architecture: x64

Am I missing an obvious trick?!

Thanks

**Comment by AlexCovizzi** [comment]
ok, it's not a bug, the extension lets you open only sqlite databases in your workspace: after executing `SQLite: Open Database in Explorer`, if you have a database in your workspace,  you should be able to select that database, like at the start of this gif:

![static/sqlite_workflow_1](https://raw.githubusercontent.com/AlexCovizzi/vscode-sqlite/master/static/sqlite_workflow_1.gif "SQLite Workflow")

Looking through the vscode api i didn't find a way to have both the option to pick the database from a list and to type the path in the input box.

**Comment by AlexCovizzi** [comment]
I solved the issue adding another option after the list of databases, the new option opens a file dialog and lets you choose a database in your file system

**Comment by AlexCovizzi** [comment]
added on release 0.3.0

**Comment by Praful** [comment]
Thanks for adding this feature!
