### ISSUE TITLE
Is it possible to include the FTS5 module?

### ISSUE THREAD

**Issue by alexkmbk** [AlexCovizzi/vscode-sqlite#207]
FTS5 module - https://www.sqlite.org/fts5.html
I would like to make a query to the  VIRTUAL TABLE of the FTS5 module.

**Comment by AlexCovizzi** [comment]
Hi @alexkmbk, I am not very familiar with that module, looking at the link there seems to be 2 oiptions:
- If it's an extension you can load it for a database by adding in the settings:
  `"sqlite.setupDatabase": { "<your db path>": { sql: ".load <FTS5 module>" } }`
- If the module has been compiled with the SQLite executable then you will need to provide the path to that executable in the setting
  `"sqlite.sqlite3": "<path to executable>"`
