### ISSUE TITLE
The viewer doesn't appear to show Boolean fields properly

### ISSUE THREAD

**Issue by colin-broderick** [AlexCovizzi/vscode-sqlite#208]
I have a boolean field named 'active' and it shows as empty:

The column does contain values, which I have confirmed by filtering using 0 or 1.

As you can see, some entries are removed when I enter zero.

![image](https://user-images.githubusercontent.com/37236262/166231990-3dadae5a-4596-4a0f-b130-91f2722685de.png)

![image](https://user-images.githubusercontent.com/37236262/166232062-53e4458f-d407-4024-9ca0-39f176cfc718.png)

**Comment by AlexCovizzi** [comment]
Hi @colin-broderick, from the screenshot that you posted it doesn't look like it's the same extension
I'll close the issue
