### ISSUE TITLE
No explorer

### ISSUE THREAD

**Issue by toorop** [AlexCovizzi/vscode-sqlite#23]
Hi, 

I've just installed your extension for vscode 1.26.1 on Ubuntu 18.04, and reload it, but when i :

- ctrl + maj +p 
- "open database in explorer"
- select DB in the list

=>  the explore doesn't open.

For info:
```
$ sqlite3 version
sqlite3 versionSQLite version 3.22.0 2018-01-22 18:45:57

$ which sqlite3
/usr/bin/sqlite3
```

Thx

**Comment by AlexCovizzi** [comment]
What's the output of `sqlite3 -version` ?

**Comment by toorop** [comment]
```
sqlite3 --version
3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt1
```
Thanks

**Comment by AlexCovizzi** [comment]
If you try to run a query does it show any error?

**Comment by toorop** [comment]
Ok i'have found the problem, it was an empty DB, my bad. Sorry for the noise :(
