### ISSUE TITLE
Support the Guid datatype

### ISSUE THREAD

**Issue by Zigby** [AlexCovizzi/vscode-sqlite#27]
Columns of type Guid are presented with the guid type 
![untitled](https://user-images.githubusercontent.com/28486683/45088474-60b38580-b109-11e8-8ea6-fb1824878056.png)
... but the columns values are not presented as Guid
![image](https://user-images.githubusercontent.com/28486683/45088542-95274180-b109-11e8-834c-205d51acae17.png)

Some tools, e.g. Database .NET are able to format the output as a GUID (instead of treating the data as UTF-8/Unicode?) 
![image](https://user-images.githubusercontent.com/28486683/45088751-3e6e3780-b10a-11e8-86a5-f6432ad40899.png)
Can support for this be added?

**Comment by AlexCovizzi** [comment]
binary data is now displayed as a hex string
