### ISSUE TITLE
The result is not showing on windows version 1.27.1

### ISSUE THREAD

**Issue by baijunty** [AlexCovizzi/vscode-sqlite#28]
Just looks like this.
![tim 20180908002602](https://user-images.githubusercontent.com/8980568/45231252-06c7e100-b2fe-11e8-9054-abccf96b8e7a.png)

But there's nothing wrong with intellij！
![2345](https://user-images.githubusercontent.com/8980568/45231923-4d1e3f80-b300-11e8-8779-03cccb6c3c5c.png)

版本: 1.27.1 (user setup)
提交: 5944e81f3c46a3938a82c701f96d7a59b074cfdc
日期: 2018-09-06T09:21:18.328Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
架构: x64

**Comment by AlexCovizzi** [comment]
Can you do:
Command Palette > Developer: Toggle Developer Tools
in the developer tools switch to console, then run the query and post here what is printed in the console.
Thanks

**Comment by baijunty** [comment]
[Extension Host] [12:34:41 PM][vscode-sqlite][INFO] Activating extension vscode-sqlite v0.3.1...
console.ts:136 [Extension Host] [12:35:43 PM][vscode-sqlite][INFO] [QUERY] SELECT * FROM `mail`;
console.ts:136 [Extension Host] [12:37:26 PM][vscode-sqlite][INFO] [QUERY] select * from mail;
console.ts:136 [Extension Host] [12:37:32 PM][vscode-sqlite][INFO] [QUERY] select * from mail;
console.ts:136 [Extension Host] [12:38:06 PM][vscode-sqlite][INFO] [QUERY] select * from mail;

It's seems not catch usefull info

**Comment by AlexCovizzi** [comment]
Can you try uninstalling the extension completely (uninstall the extension, close vscode and then reopen it), and then reinstall it and see if the problem persists?
If it's still not working i need you to run the query and with the page titled SQLite open go to:
Command Palette > Developer: Open Webview Developer Tools
Post here everything from Console and then go in Elements
body > iframe > #document > html, right click > copy > copy element
Thanks

**Comment by baijunty** [comment]
I tryed to reinstall it but not work.
then I edit the \out\resultview\index.js file insert some log  like this
![2345](https://user-images.githubusercontent.com/8980568/45257233-65ac5980-b3d5-11e8-9f04-b76e20f97434.png)

then get the result is
![sdfwer](https://user-images.githubusercontent.com/8980568/45257280-0d298c00-b3d6-11e8-97fd-42207d0c2482.png)


I guess reason is the empty msgQueue so i can't handle the result.
The result webview html is default  status
`
<webview tabindex="-1" partition="webview1536429530608" disableblinkfeatures="Auxclick" disableguestresize="" webpreferences="contextIsolation=yes" preload="file:///d:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/parts/webview/electron-browser/webview-pre.js" src="data:text/html;charset=utf-8,%3C%21DOCTYPE%20html%3E%0D%0A%3Chtml%20lang%3D%22en%22%20style%3D%22width%3A%20100%25%3B%20height%3A%20100%25%22%3E%0D%0A%3Chead%3E%0D%0A%09%3Ctitle%3EVirtual%20Document%3C%2Ftitle%3E%0D%0A%3C%2Fhead%3E%0D%0A%3Cbody%20style%3D%22margin%3A%200%3B%20overflow%3A%20hidden%3B%20width%3A%20100%25%3B%20height%3A%20100%25%22%3E%0D%0A%3C%2Fbody%3E%0D%0A%3C%2Fhtml%3E" guestinstance="1" class="ready" style="width: 100%; height: 100%; outline: 0px;"></webview>`

**Comment by AlexCovizzi** [comment]
It should work like this: after executing the query, the extension opens a webview that shows an html page ([this html page](https://gist.github.com/AlexCovizzi/e3922ffb34313b42fcbdceeee419d64a), you can find it in  `\out\resultview\htmlcontent\index.html`), the html page then sends a request to the extension for the resultSet, in your case the msgQueue is empty because the html page is not loaded so it's sending nothing.

Doing some testing i was able to replicate your case by deleting the html file, so maybe you are missing the file `\out\resultview\htmlcontent\index.html` or maybe the extension can't read it?

Can you try this: add in the file `\out\resultview\customview.js` between line 25-26 a console.log to print the variables `htmlPath` (the path of index.html), and `html` (the content of the file).

**Comment by AlexCovizzi** [comment]
ok, keep me updated

**Comment by baijunty** [comment]
I had reinstall several times to make sure it,we must install the vscode program to the  system's disk (the same with  extensions disk).Then the 'vscode-resource' scheme works very well,otherwise the vscode will fail to load files without error message.

**Comment by AlexCovizzi** [comment]
Does it work now?

**Comment by baijunty** [comment]
Yes.
