### ISSUE TITLE
Table PK info in ColumnItem 

### ISSUE THREAD

**Issue by fotospiro** [AlexCovizzi/vscode-sqlite#3]
When retrive column infos (file src/explorer/explorerTreeProvider.ts line 82), PK property could be ">0", not "==1" if table has two column for primary key

![schermata 2018-06-28 alle 11 37 44](https://user-images.githubusercontent.com/40659655/42026694-1fa9fdca-7ac8-11e8-9bbc-020604f85d3b.png)

EXAMPLE:

`CREATE TABLE employees ( company_id TEXT , emp_id TEXT , company_sbj_id TEXT , subject_id TEXT , hire_date INTEGER , resign_date INTEGER , sync_stamp INTEGER , **PRIMARY KEY (company_id,emp_id)** )`

![schermata 2018-06-28 alle 11 36 03](https://user-images.githubusercontent.com/40659655/42026739-3c20639a-7ac8-11e8-9407-9f89e0fb72d4.png)

**Comment by AlexCovizzi** [comment]
didn't know that, thanks for the info, i'll fix it
