### ISSUE TITLE
freezes after "Choose another database"

### ISSUE THREAD

**Issue by zingdle** [AlexCovizzi/vscode-sqlite#31]
When I tried to use a database by
1. `SQLite: Use Database`
2. `Choose another database`

vscode freezes after the file dialog opened.

I'm using vscode 1.27.2. Ubuntu 16.04. GNOME 3.18.5

**Comment by AlexCovizzi** [comment]
This seems to be a bug with vscode, see [this issue](https://github.com/Microsoft/vscode/issues/52778).
A workaround is to use arrow keys and Enter to select `Choose another database` instead of clicking on it.
