### ISSUE TITLE
Database not closed?

### ISSUE THREAD

**Issue by focussing** [AlexCovizzi/vscode-sqlite#33]
When I do first:
SQLite: Open Database in Explorer   Open the selected database in the sidebar explorer.

I see in my folder that 2 temporary files are generated:
<sqlitefilename>-shm and <sqlitefilename>-shm

And then:
SQLite: Close Explorer Database   Remove the selected database from the explorer.

I see in my folder that the 2 temporary files are still present.
When I use a program like MesaSQLITE and close a database, these files do disappear.

**Comment by AlexCovizzi** [comment]
I'm not able to reproduce this behaviour.
I also tried setting Write-Ahead Logging using `PRAGMA journal_mode=WAL;` (looking [here](https://www.sqlite.org/wal.html) it seems to be the cause for the creation of the shm file)
but running `SQLite: Open Database in Explorer` doesn't generate any -shm files
