### ISSUE TITLE
binary path is not recognized as a command in Windows environment

### ISSUE THREAD

**Issue by mandel59** [AlexCovizzi/vscode-sqlite#34]
When sqlite3 command is given as a binary path, vscode-sqlite warns that the given path is not recognized as a command.
![image](https://user-images.githubusercontent.com/1079715/46913717-697f5d00-cfcd-11e8-9f51-0158b25d5541.png)

This would be caused by the issue of the `command-exists` package already resolved. https://github.com/mathisonian/command-exists/pull/21

**Comment by AlexCovizzi** [comment]
Thanks, I'll fix it asap
