### ISSUE TITLE
Empty view by "Run Query" or select menu "Show Table" on Windows

### ISSUE THREAD

**Issue by AlexeyErofeev** [AlexCovizzi/vscode-sqlite#36]
![image](https://user-images.githubusercontent.com/5891123/47366178-cf629780-d6e5-11e8-81ea-0ad813f0ffa8.png)
But it shows db structure in explorer - silently, without pragma logs or another, i placed "sqlite.logLevel": "DEBUG" in settings.json, but it has no visible effect

**Comment by AlexCovizzi** [comment]
If you do `command palette` > `Developer: Toggle Developer Tools` and then run the query, does it show any error messages?

**Comment by Pardych** [comment]
full log in dev tools console for actions "open vs code", "use databse", "open db in explorer", "show table":
[Extension Host] Looking for parseable documents...
console.ts:136 [Extension Host] [6:18:40 PM][vscode-sqlite][INFO] Activating extension vscode-sqlite v0.3.1...
console.ts:136 [Extension Host] Found no documents
console.ts:136 [Extension Host] [6:19:34 PM][vscode-sqlite][INFO] [QUERY] SELECT * FROM `alarms`;

**Comment by AlexCovizzi** [comment]
Looks very similar to [this issue](https://github.com/AlexCovizzi/vscode-sqlite/issues/28).
It seems to be caused by having VSCode and the extensions in different disks.

**Comment by Pardych** [comment]
Exactly my case. Reinstall and it works! Thanx and sorry, I didnt notice that issue.

**Comment by AlexCovizzi** [comment]
Fixed in 0.5.0
