### ISSUE TITLE
Fails to open a table with Chinese name.

### ISSUE THREAD

**Issue by jryx0** [AlexCovizzi/vscode-sqlite#37]

**Comment by AlexCovizzi** [comment]
Windows?

**Comment by jryx0** [comment]
window 10

**Comment by AlexCovizzi** [comment]
This is very similar to [this issue](https://github.com/AlexCovizzi/vscode-sqlite/issues/32).

I tried different things, but it looks like the sqlite executable on Windows does not support unicode characters, so opening a database from a path with unicode chars, or executing a query with unicode chars doesn't work (you can try it yourself by opening the database using the sqlite executable in the extension's `bin` directory).

**Comment by jryx0** [comment]
Sorry for the late reply, I changed  to none-unicode chars. Thanks
