### ISSUE TITLE
[feature-request] Add support for SQLCipher

### ISSUE THREAD

**Issue by lualebu** [AlexCovizzi/vscode-sqlite#39]
From the[ GitHub page](https://github.com/sqlcipher/sqlcipher):

>SQLCipher extends the SQLite database library to add security enhancements that make it more suitable for encrypted local data storage such as on-the-fly encryption, tamper evidence, and key derivation. Based on SQLite, SQLCipher closely tracks SQLite and periodically integrates stable SQLite release features.

Support could be added by including the required SQLCipher bins, and adding a 'provider selector' when opening databases.

**Comment by AlexCovizzi** [comment]
Closing this issue
I'm not sure how SQLCipher works, if it's an extension you can load it in the new setting `sqlite.setupDatabase` that has been added in version 0.13.0, if it's an executable then you should provide the path in the setting `sqlite.sqlite3`
