### ISSUE TITLE
More infos in Explorer Tree

### ISSUE THREAD

**Issue by fotospiro** [AlexCovizzi/vscode-sqlite#4]
Underline/bold a primary key field, add if it's a nullable field

Example:
Employess
**id** : integer (null; def="1")

**Comment by AlexCovizzi** [comment]
right now you can see more data about the field by hovering over it, it still misses the default value though.
About the underline/bold i'll see what i can do, i don't know if it's possible with the current vscode api

**Comment by fotospiro** [comment]
Tooltip it's great!! For primary key (I think it's an important information) you could use an icon??

PS Great extension!!

**Comment by AlexCovizzi** [comment]
good idea, i'll add an icon. i could also add an icon for the foreign key

**Comment by fotospiro** [comment]
and an empty icon for other fields so they'll be aligned

**Comment by AlexCovizzi** [comment]
i think i'll go with something like MySQL Workbench, so you also have information about nullable fields
![Example](https://dev.mysql.com/doc/workbench/en/images/wb-sakila-tutorial.png)
