### ISSUE TITLE
[feature-request] Add support for Attached database queries and project configuration

### ISSUE THREAD

**Issue by Wayofthesin** [AlexCovizzi/vscode-sqlite#43]
We are currently working on a project with multiple sqlite database files. Some of the queries are executed cross-database using sqlite ATTACH clause.

For this project it is necessary to be able to attach multiple databases with given names and preview them in explorer. Current version does not seem to allow to do it.

The further improvement would be the project configuration that automatically opens multiple databases with given aliases. Imagine the following configuration:

```json
{
    "sqlite3": {
        "databases": {
            "master-only": "/database/master.db",
            "master-with-secondary": [
                { "database": "/database/master.db", "alias": "master" },
                { "database": "/database/secondary.db", "alias": "secondary" }
            ]
        }
    }
}
```

With such configuration user should be able to execute the following command:
`SQLite: Connect to predefined`

and then select `master-only` or `master-with-secondary` from the drop-down to connect. Note that the database path is relative to root directory so this configuration only makes sense in environment configuration scope.

**Comment by AlexCovizzi** [comment]
To execute a query cross-database you can create an ```sql``` file, write the ```ATTACH``` statement and then the query. For example:

```
sql_query.sql

ATTACH "/database/secondary.db" AS secondary;

SELECT * FROM master.table1 JOIN secondary.table2;
```

And then run the query using the master database.

**Comment by AlexCovizzi** [comment]
Support for `ATTACH` will be added in version 0.7.
However it won't be implemented as you suggested.

Right now the extension uses the path to identify the database, this keeps the extension simple to use and to manage.

Keeping that in mind I thought that the best way to implement the database configuration is to use globs, so, for example, the configuration:

```
"sqlite.databaseConfig": {
    "**/*/master.db": {
        "attach": [
            { "database": <db path>, "alias": <db alias> }
        ]
    }
}
```

means that every time you do an operation (like a query or opening in the explorer) with a database named 'master.db' in your workspace, it will automatically attach the database defined in 'attach'.

The only problem with this implementation is that it does not allow for multiple configurations for the same database.

This is still under development, so every suggestion is welcome.
