### ISSUE TITLE
[feature-request] Add support for in-memory database

### ISSUE THREAD

**Issue by vor0nwe** [AlexCovizzi/vscode-sqlite#44]
When selecting an SQLite database from the status bar, could the list always include an item for an [in-memory database](https://www.sqlite.org/inmemorydb.html)?

SQLite accepts the special path `:memory:` to open a transient memory-only database. Its contents will be lost when the database connection is closed. This makes it ideal for quick testing of a complete SQL script, without having to save stuff to disk. Also, I often use this as a starting point for [attaching](https://www.sqlite.org/lang_attach.html) several other databases, each with their specific alias.

**Comment by AlexCovizzi** [comment]
Added in version 0.4.0

**Comment by smargoli2** [comment]
Was this feature removed in version 0.5.0? I don't see it
