### ISSUE TITLE
No result in SQLite when i run "SELECT * FROM COMPANY"

### ISSUE THREAD

**Issue by JiuMengDz** [AlexCovizzi/vscode-sqlite#50]
![snipaste_2019-01-25_14-12-55](https://user-images.githubusercontent.com/40727230/51728475-58a1b580-20ab-11e9-840e-56da5e35cf67.png)

**Comment by AlexCovizzi** [comment]
Hi @JiuMengDz,
could it be the same problem as #36?

**Comment by AlexCovizzi** [comment]
Fixed in version 0.5.0
