### ISSUE TITLE
Resources in WebView are not loaded in dev host environment on Windows

### ISSUE THREAD

**Issue by mandel59** [AlexCovizzi/vscode-sqlite#51]
In deb host environment, resources in WebView are not loaded although the SQLite tab has been open:
![000](https://user-images.githubusercontent.com/1079715/51758462-17d88980-2109-11e9-972f-55c7deb1bac4.PNG)
VS Code is installed at `C:\Users\mande\AppData\Local\Programs\Microsoft VS Code`, and my dev repository is put at `D:\mande\dev\vscode-sqlite`.

Developer Console shows "failed to load resource" errors:
![001](https://user-images.githubusercontent.com/1079715/51758478-23c44b80-2109-11e9-9493-82988aad02e5.PNG)

In the following line, the value of `this.resourcesPath` is `"d:\mande\dev\vscode-sqlite\out\resultview\htmlcontent"` in my dev environment. 
https://github.com/AlexCovizzi/vscode-sqlite/blob/1cb7fe1cd596cd61781c40f547d2837dbac23b4a/src/resultview/customview.ts#L65

So `Uri.parse` parses it as:
- schema: `"d:"`
- path: `"\mande\dev\vscode-sqlite\out\resultview\htmlcontent"` 

![005](https://user-images.githubusercontent.com/1079715/51759838-78b59100-210c-11e9-92ba-252d9afebd3e.PNG)

And then the schema is rewriten, so the result is `"vscode-resource:\mande\dev\vscode-sqlite\out\resultview\htmlcontent"`, which misses the drive letter `d:`.

**Comment by AlexCovizzi** [comment]
Now i understand why you changed `Uri.parse` to `Uri.file` in #49, i'll merge #52 asap.
Thank you again!
