### ISSUE TITLE
intellisense

### ISSUE THREAD

**Issue by mammadkoma** [AlexCovizzi/vscode-sqlite#55]
Please add intellisense for tables name in new query
Thanks

**Comment by AlexCovizzi** [comment]
Fixed in version 0.5.1

**Comment by mammadkoma** [comment]
I have SQLite 0.5.1 extension but its intellisense only show sql keywords.
Could you add features of [sqlitestudio](https://sqlitestudio.pl/index.rvt) to your extension?
(Table names intellisense, alter table , ...)

**Comment by AlexCovizzi** [comment]
For table and column names you need to first bind the document to a database using the command ```SQLite: Use Database```
