### ISSUE TITLE
Allow drag-drop from Explorer Side Bar

### ISSUE THREAD

**Issue by ffes** [AlexCovizzi/vscode-sqlite#57]
Allow to drag and drop a table or column to any edit window. The name of the selected item should be inserted at the cursor location. This way it is easy to use those names in a source file.

**Comment by AlexCovizzi** [comment]
Unfortunately drag&drop is not available in the vscode API, i can however add another option to copy the name of the table/column in the clipboard

**Comment by ffes** [comment]
Copy to the clipboard would be helpful as well 👍

**Comment by AlexCovizzi** [comment]
Added in version 0.6.0 options in the sqlite explorer to copy database path and table/column name
