### ISSUE TITLE
New Query from table

### ISSUE THREAD

**Issue by ffes** [AlexCovizzi/vscode-sqlite#58]
When I right-click a table, it has an option `Show Table`. Could you add an option `New Query` as well?

Ideally it would open a query like this:

```sql
SELECT column1
     , column2
     , column3
FROM table
```

but simply `SELECT * FROM table` would already be helpful

**Comment by AlexCovizzi** [comment]
Added in version 0.6.0 options `New query [Select]` and `New query [Insert]` in the sqlite explorer to create sql files.

**Comment by ffes** [comment]
Thanks, works great!
