### ISSUE TITLE
Change connection to enforce fk constraints?

### ISSUE THREAD

**Issue by baodad** [AlexCovizzi/vscode-sqlite#60]
Is there any way to change the way vscode-sqlite connects so as to enforce fk constraints? "foreign keys=True" in the connection string?

**Comment by baodad** [comment]
It looks like vscode-sqlite uses sqlite command line.  Perhaps adding a line after line 17 of /src/sqlite/sqlite.ts for ``` `-cmd`, `.dbconfig enable_fkey on` ``` would make it so vscode-sqlite enforced foreign keys by default.  sqlite cli will accept multiple -cmd switch arguments.

**Comment by AlexCovizzi** [comment]
This will be added in the next minor update (0.6.0).

It will be added as an attribute to configure the database, the idea is to have a setting like this:

```
"sqlite.databaseConfig": {
  "**/*.db": {
    "enableForeignKeys": "true",
  }
}
```

So that it can be set true or false depending on the database you are using.

**Comment by MaxenceG2M** [comment]
Hi!

I use this setting in my settings.json, but it doesn't seem to be taken into account.
Planned for another version?

**Comment by AlexCovizzi** [comment]
Hi @MaxenceG2M, I did not implement this feature yet. I started implementing it last year but then I got caught up with my master's thesis and I stopped working on it. However, now that I am done with my thesis, I have some free time, so I'll definetely continue.

**Comment by tallguyjenks** [comment]
can this PLEASE be implemented? Isn't it kind of an essential piece. of functionality to have foreign key constraints on tables? I was trying to implement them until I found out through this still open issue that its currently not possible.
