### ISSUE TITLE
Incorrect syntax errors?

### ISSUE THREAD

**Issue by lraulin** [AlexCovizzi/vscode-sqlite#62]
It seems like it's often showing syntax errors in code that is correct as far as I can tell (admittedly, I'm not very good at SQL), and works just fine.

For example, this is showing "Incorrect syntax near 'SELECT'.  Expecting EDGE_TYPE, FILETABLE, or ID." for the first CREATE, and "Incorrect syntax near 'TEMP'." for the second. But the code editor in DB Browser for SQLite shows no syntax errors, and it produces the expected output with no errors in both DB Browser and the CLI.

```
DROP TABLE IF EXISTS temp.a;
DROP TABLE IF EXISTS temp.b; 

CREATE TEMP TABLE temp.b AS SELECT queried_at, datetime, domain, type, answers
FROM records
WHERE queried_at = ( SELECT MAX(queried_at) FROM records );

CREATE TEMP TABLE temp.a AS SELECT queried_at, datetime, domain, type, answers
FROM records
WHERE queried_at = ( 
    SELECT MAX(queried_at)
    FROM records
    WHERE queried_at NOT IN ( SELECT MAX(queried_at) FROM records ) );

SELECT a.queried_at, b.queried_at, a.domain, a.type, a.datetime, a.answers, b.datetime, b.answers FROM a INNER JOIN b ON a.domain = b.domain AND a.type = b.type WHERE a.answers <> b.answers;
```

**Comment by AlexCovizzi** [comment]
Hi @lraulin, i tried to run your query using a table similar to your `records` ([see this query](https://gist.github.com/AlexCovizzi/351e6977c1017d7e895f5b696a255227)), and i used `:memory:` as database but i didn't get any error.
Can you tell me what version of the extension are you using, and your OS?

**Comment by lraulin** [comment]
vscode-sqlite 0.5.3
MacOS Mojave 10.14.3
VS Code 1.32.1

It looks like this happens if I don't change "SQL language" from MSSQL to "None" (which are the only two options) before changing the main language mode from SQL to SQLite. I guess it's still trying to use MSSQL, and the errors would be correct if it were MSSQL because SQLite is not valid MSSQL?

But if I change SQL language to None and then change the language mode to SQLite... Completion works for my tables when I'm connected to the database, but VS Code doesn't show any syntax errors no matter what I do. I can type complete gibberish, and VS Code doesn't show any errors.

Connecting to the database and putting "-- sqlite" on the first line don't seem to make a difference.

Thanks for your help!

**Comment by AlexCovizzi** [comment]
> But if I change SQL language to None and then change the language mode to SQLite... Completion works for my tables when I'm connected to the database, but VS Code doesn't show any syntax errors no matter what I do. I can type complete gibberish, and VS Code doesn't show any errors.

The extension does not support linting for now, it will be added in the future.

**Comment by lraulin** [comment]
Ok. I see. Thanks!
