### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Chandramouli1997** [AlexCovizzi/vscode-sqlite#65]
- Issue Type: `Performance`
- Extension Name: `vscode-sqlite`
- Extension Version: `0.6.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\CHAN\alexcvzz.vscode-sqlite-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by AlexCovizzi** [comment]
You forgot to upload the file `cpuprofile.txt`

**Comment by AlexCovizzi** [comment]
Closed in favour of #110
