### ISSUE TITLE
Missing spellfix1 workaround

### ISSUE THREAD

**Issue by alientechsw** [AlexCovizzi/vscode-sqlite#66]
Some data bases are created with virtual tables please see [spellfix1](https://www.sqlite.org/spellfix1.html). Since this is not included in the official sqlite3 binaries.. the I found this workaround on [stackoverflow](https://stackoverflow.com/questions/38425835/reflecting-sqlite-database-with-spellfix1-tables)

SQLite is an embedded database, and can be customized. The Plex Media Server has added the spellfix1 extension; the documentation says:

> The spellfix1 virtual table is not included in the SQLite amalgamation and is not a part of any standard SQLite build. It is a loadable extension.

To be able to access this table, you'd have to compile this extension yourself, and load it into the Python database connection.

If you don't actually need to do spell checks, you can create a copy of the database without that virtual table:

convert the database to text with the sqlite3 command-line shell:
```
sqlite3 some/where/...library.db ".dump" > library.sql
```
(this works without the module installed);

remove the creation of the virtual table from the SQL script; it's a line looking like this:
```
INSERT INTO sqlite_master(type,name,tbl_name,rootpage,sql)VALUES('table','xxx','xxx',0,'CREATE VIRTUAL TABLE xxx using spellfix1(...)');
```
create a new database from that script:
```
sqlite3 new.db < library.sql
```

**Comment by AlexCovizzi** [comment]
Extensions can now be loaded whenever a database is opened by using the setting `sqlite.setupDatabase` introduced in version 0.13.0
