### ISSUE TITLE
[feature-request] Ability to handle database or sql files with non-standard extensions

### ISSUE THREAD

**Issue by pccasto** [AlexCovizzi/vscode-sqlite#69]
I have a sqlite3 database file that is used as a basis for building other files. It is named mydbname.db.default.  There doesn't seem to  be a way to use this extension to examine the file. I have tried in the editor, and could not find a way to "show as", and manually select the sqlite viewer extension.

I also think I found a dialog box within the extension that allowed me to browse for sqlite3 database files to open, but now I can't find/reproduce that. However even in the file-browser window, the only choices were ".db .db3 .sdb .s3db .sqlite .sqlite3"  There was no ability to look at *.* files, and select that way.

My problem was with a database file, but I suppose there might be some sql files with the same issue. So they should be considered in the same way.

Thanks for considering this,
Paul

**Comment by AlexCovizzi** [comment]
This will be fixed as soon as i have time to work on it, it shouldn't take long.

**Comment by pccasto** [comment]
No worries about the timing.  Thanks for working it in when you get a chance.
~paul

**Comment by bjornreppen** [comment]
.mbtiles is a popular SQLite  file extension with the GIS crowd, Mapbox Vector Tiles https://github.com/mapbox/vector-tile-spec

**Comment by AlexCovizzi** [comment]
Added in version 0.7.0 in the setting `sqlite.databaseExtensions`

**Comment by pccasto** [comment]
Thank you!
