### ISSUE TITLE
Documentation doesn't mention how to open a file

### ISSUE THREAD

**Issue by michaelherger** [AlexCovizzi/vscode-sqlite#70]
I can't figure out how to open a database file... When asked for a filename I've pasted a path I copied from the console, typed filenames only etc. But then nothing happens. How would I do this? I watched the animated GIF frame by frame...

**Comment by AlexCovizzi** [comment]
Hi @michaelherger, after running the command `SQLite: Open Database`, the extension should show a dialog with the databases in your workspace and an option `Choose a database from file`. To open the database you just click on the database that you want to open, or you choose one from you system.

Note that right now the supported file extensions for the databases are: db, db3, sqlite, sqlite3, sdb, s3db; so if your database does not have any of these extensions you won't be able to open it (see #69).

**Comment by michaelherger** [comment]
Oh, I see: the file has to be in my workspace? No opening from any place? That's a pity, as my data lives outside my workspace... I'll have to play with symlinks or the like.

**Comment by michaelherger** [comment]
I changed the title of this issue to make clear what the actual problem is. There's no word about how to use the add-on. And the requirement of having the db file in the workspace IMHO is not the most obvious.

**Comment by AlexCovizzi** [comment]
Sorry @michaelherger, maybe I was not clear, you can open a database from any place by selecting `Choose a database from file`

**Comment by michaelherger** [comment]
Hmm... that's odd: that's certainly what I did the first time around. But it didn't work. Now I'm sitting at another computer, and it's working as expected. Oh well... Thanks for the help!
