### ISSUE TITLE
Feature request: run only one query in the file

### ISSUE THREAD

**Issue by LordWolfenstein** [AlexCovizzi/vscode-sqlite#74]
On many SQL tools when you have a *.sql file with many queries you can choose to only run the query your cursor is currently on. I miss that feature in this tool.

**Comment by AlexCovizzi** [comment]
Hi @LordWolfenstein, this feature already exists (kind of), right now you can select some text and execute only the query selected using the same command `Run Query`.
Maybe i should make it more explicit, and add a new command `Run Selected Query`, what do you think?

**Comment by LordWolfenstein** [comment]
Yes. But I mean something like pressing a hotkey (for example CTRL+r) and it runs the query your cursor is on. That is so much faster when when you just want to run one query and got loads in front of you and want to alternate fast. MySQL Workbench and SQL Pro have that feature.

**Comment by LucidToday** [comment]
+1 for this feature, it's a fantastic productivity aid in tools that have it. You can have a requirement that statements must end with a ; to make finding the end of queries easier.

**Comment by AlexCovizzi** [comment]
Ok, I'm implementing it right now, it should be ready soon.

**Comment by LucidToday** [comment]
Thanks Alex, you are awesome!

**Comment by AlexCovizzi** [comment]
Published in version 0.8.0
