### ISSUE TITLE
Opening Table just gives blank screen

### ISSUE THREAD

**Issue by Benzidrine** [AlexCovizzi/vscode-sqlite#79]
VSCode version 1.38.1
Working through tutorial https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-2.2&tabs=visual-studio-code

Clicking on a table or attempting to make a new screen just causes the working area to go black and I need to close and reopen vscode to continue.

**Comment by AlexCovizzi** [comment]
Hi @Benzidrine, sorry for the late response, are you still having this problem?

**Comment by AlexCovizzi** [comment]
Feel free to re open the issue if you are still having this problem.
