### ISSUE TITLE
VSCode can't install the extension on MacOS

### ISSUE THREAD

**Issue by Fogetti** [AlexCovizzi/vscode-sqlite#8]
VSCode can't install the extension by clicking the install button. It shows the "Install manually" button instead and then offers to install from the VSIX file.

The installation from the VSIX subsequently also fails. More precisely it seems to succeed but after reloading VSCode the commands don't show up in the command palette and the extension shows a blue "Reload" button in the list of installed extensions (which I clicked a few times but it never succeeds).

VSCode version 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1)
OS version: macOS High Sierra 10.13.3 (17D102)
Extension version: 0.1.2

**Comment by AlexCovizzi** [comment]
The extension uses the Webview API that is available from version 1.23 of vscode, updating VSCode should solve the problem
