### ISSUE TITLE
Does anyone know how to use this extension?

### ISSUE THREAD

**Issue by mykevinjung** [AlexCovizzi/vscode-sqlite#80]
Silly question. Anyone knows how to use this extension? I tried to find how to use but could not for 30 minutes. Looks like I need to choose database from file. I guess that the file includes a configuration on the database connection string. How should I configure "database from file"?

![image](https://user-images.githubusercontent.com/6750331/65211434-87fa9d80-da53-11e9-8f27-151406e484c1.png)

**Comment by AlexCovizzi** [comment]
Hi @mykevinjung,
After running the command `SQLite: Open Database` you should be able to to see a list of file names and an option `Choose database from file`.
To open the database simply click on the database you want to open or select one from file using the `Choose your database from file` option.
The database should be opened in the file explorer.
