### ISSUE TITLE
No support for SQLite dot commands?

### ISSUE THREAD

**Issue by frank-wang-yifei** [AlexCovizzi/vscode-sqlite#81]
Hi Alex, first **thank you** for bringing this great extension to the community! Yeah I know people usually contact the author when there're issues (rather than compliments...).

Now time for my issue: I used to use SQLite command line tool (sqlite3) to create and update some .db files. The SQL script files (say, `script.sql`) I use contain mixed dot commands (e.g. `.open db_file_name.db`) and SQL statements (e.g. `INSERT INTO table VALUES (...);`). Then I run this script in sqlite3 with `.read script.sql` command to get the job done.

After I got this extension I tried to run my script with Ctrl+Shift+Q, but got errors at all those dot commands. Does this mean the extension has no support for them yet?

If so no problem. I can still use sqlite3 to run the dot commands and get the .db files set up. After that I can use VSCode + SQLite extension to run the pure SQL statements. But please consider adding support for the dot commands (and `PRAGMA` command) in future - that way users can completely bypass command line work and stick to "scripted workflow".

Cheers!

**Comment by AlexCovizzi** [comment]
Hi @frank-wang-yifei,
dot commands are not supported, but `PRAGMA` commands should work.
I'll work on adding support for dot commands when i have more time on my hands.

**Comment by frank-wang-yifei** [comment]
Thanks - looking forward to the new support!
