### ISSUE TITLE
Error on empty string.

### ISSUE THREAD

**Issue by golf14** [AlexCovizzi/vscode-sqlite#82]
When a querry has empty string neither Run Query nor Run Selected Query works properly.
`SELECT length(' ');`
Returns 1 (note the space).
`SELECT length('');`
causes an error.

As a workaround one can use
`SELECT length(trim(' '));`
which works fine.

**Comment by ShadowFoxNixill** [comment]
Seconded, scripts with empty strings behave strangely with no error shown.
