### ISSUE TITLE
Please support auto-completion

### ISSUE THREAD

**Issue by psychelzh** [AlexCovizzi/vscode-sqlite#9]
It will be better that we could use <kbd>Tab</kbd> to autocomplete queries.

**Comment by AlexCovizzi** [comment]
syntax highlighting, autocompletion and snippets are on my to-do list, they will probably come in the next month

**Comment by AlexCovizzi** [comment]
Forgot to close this earlier. autocompletion have been implemented in version 0.3.1

**Comment by kylechartio** [comment]
Cool extension. I notice it didn't seem to autocomplete builtins such as max/abs etc.
