### ISSUE TITLE
Stopped Working - console message - Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by bravedave** [AlexCovizzi/vscode-sqlite#93]
This most excellent plugin has suddenly stopped working for me
It works on my seemingly identical notebook - the only difference in the environments - my desktop is on a the _slow_ Windows Insider channel.

In the VS Code footer a message briefly appears _activating plugins_, and then nothing. The attached snip is from the developer console, the first error reads:

- Cannot read property 'toUpperCase' of undefined

![image](https://user-images.githubusercontent.com/2217137/71853270-8cdc7d80-3126-11ea-92af-7bd155fd0816.png)

**Comment by AlexCovizzi** [comment]
Hi @bravedave, it seems that the table's schema is missing the column "type". Can you check with the command `PRAGMA table_info(<name of your table>);`?
Thanks

**Comment by bravedave** [comment]
Sure - what output would you like:

```
PRAGMA table_info('invoices');
cid         name        type        notnull     dflt_value  pk
----------  ----------  ----------  ----------  ----------  ----------
0           id          INTEGER     0                       1
1           state       TEXT        0                       0
2           state_chan  TEXT        0                       0
3           state_chan  TEXT        0                       0
4           state_chan  TEXT        0                       0
```

**Comment by bravedave** [comment]
Ok, more information

- I opened alexcvzz.vscode-sqlite-0.8.1\out\sqlite\schema.js
- and inserted the line at 32 : console.log(columnQuery);
- it errors when the value is PRAGMA table_info('changes:   0   total_changes: 0');

So I guessed this doesn't affect you, or my notebook;
my .sqliterc file had the line:
`.changes on`

changed to
`.changes off`

so now - all good, thanks for your help (and your comment did help)

cheers

**Comment by bmccorm2** [comment]
Sorry for reviving this but what was your solution?  I am having the same issue and cannot find the file (schema.js) you reference above.
