### ISSUE TITLE
Columns with spaces in column names cause incorrect query generation

### ISSUE THREAD

**Issue by aleybovich** [AlexCovizzi/vscode-sqlite#97]
I have a table with a column like 'Connection url' and when I right-click the table in the sidebar and choose 'New Query [Select]', the generated query has the column name without quotes, which obviously fails to execute. The fix should be surrounding such columns that have spaces or special characters with a single quote.

instead of `SELECT Connection url FROM blah`
it should generate `SELECT 'Connection url' FROM blah`

**Comment by AlexCovizzi** [comment]
Hi @aleybovich! The issue has been fixed in master. Columns with spaces in the name are wrapped in `` ` `` 
Example: ``SELECT `Connection url` FROM blah``
