### ISSUE TITLE
Extension will not open database in explorer if view definition invalid in schema

### ISSUE THREAD

**Issue by grahamito** [AlexCovizzi/vscode-sqlite#99]
I think this is an issue, but maybe i am just being dumb: 

When db explorer tries to open the sqlite db, it fail with error if there is a view in the db whose definition is invalid. 

The view can be invalid if it is based on a table. and then the table is deleted, or the select statement  references a column that does not exist.

Example: View references column named "material" that does not exist. 

``` sql
e.g. create view 
CREATE VIEW v as 
SELECT material
FROM t;
```

Behavior: db explorer does not open in sidebar, displays 

![image](https://user-images.githubusercontent.com/1020954/79693505-5658e780-826b-11ea-80e4-1c3158f87cc5.png)

Desired behavior db explorer should open and allow you to see the database tables and views

**Comment by AlexCovizzi** [comment]
Hi @grahamito! The issue has been fixed in master. Checkout [Pull Request #101](https://github.com/AlexCovizzi/vscode-sqlite/pull/101)

**Comment by grahamito** [comment]
Thanks for fixing this so promptly. I appreciate it!
